"""persist reviewer-aware photo validation batches and retry scope

Revision ID: 0e8c65fbe1ca
Revises: 67bc03d440b2
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0e8c65fbe1ca"
down_revision: str | None = "67bc03d440b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_reviewers",
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_reviewers")),
        sa.UniqueConstraint("display_name", name=op.f("uq_photo_reviewers_display_name")),
    )
    op.create_table(
        "photo_review_batches",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("current_position", sa.Integer(), nullable=False),
        sa.Column("current_filter", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_photo_review_batches_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["photo_reviewers.id"],
            name=op.f("fk_photo_review_batches_created_by_photo_reviewers"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["photo_reviewers.id"],
            name=op.f("fk_photo_review_batches_reviewer_id_photo_reviewers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_review_batches")),
    )
    op.create_table(
        "photo_review_batch_items",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("selection_session_id", sa.Uuid(), nullable=False),
        sa.Column("automatic_rank", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending','confirmed','skipped','needs_attention')",
            name=op.f("ck_photo_review_batch_items_review_state"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["photo_review_batches.id"],
            name=op.f("fk_photo_review_batch_items_batch_id_photo_review_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["photo_reviewers.id"],
            name=op.f("fk_photo_review_batch_items_reviewer_id_photo_reviewers"),
        ),
        sa.ForeignKeyConstraint(
            ["selection_session_id"],
            ["photo_selection_sessions.id"],
            name=op.f("fk_photo_review_batch_items_selection_session_id_photo_selection_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_photo_review_batch_items_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("batch_id", "position", name=op.f("pk_photo_review_batch_items")),
        sa.UniqueConstraint(
            "batch_id", "submission_id", name=op.f("uq_photo_review_batch_items_batch_id")
        ),
    )
    op.add_column(
        "campaign_preparation_jobs",
        sa.Column("submission_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("photo_selection_sessions", sa.Column("reviewer_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_photo_selection_sessions_reviewer_id_photo_reviewers"),
        "photo_selection_sessions",
        "photo_reviewers",
        ["reviewer_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_photo_selection_sessions_reviewer_id_photo_reviewers"),
        "photo_selection_sessions",
        type_="foreignkey",
    )
    op.drop_column("photo_selection_sessions", "reviewer_id")
    op.drop_column("campaign_preparation_jobs", "submission_scope")
    op.drop_table("photo_review_batch_items")
    op.drop_table("photo_review_batches")
    op.drop_table("photo_reviewers")
    # ### end Alembic commands ###
