"""campaign preparation review account pools and ranking feedback

Revision ID: 14de7a34ff11
Revises: 42a4c1b530ea
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "14de7a34ff11"
down_revision: str | None = "42a4c1b530ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("submissions", sa.Column("photo_source", sa.String(50), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_ranking_models",
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("feature_schema_version", sa.Integer(), nullable=False),
        sa.Column("training_choices", sa.Integer(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coefficients", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_ranking_models")),
    )
    op.create_table(
        "photo_ranking_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_ranking_preferences")),
    )
    op.create_table(
        "campaign_accounts",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("max_submissions", sa.Integer(), nullable=False),
        sa.Column("assigned_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("max_submissions > 0", name=op.f("ck_campaign_accounts_quota_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_campaign_accounts_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_accounts_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("campaign_id", "account_id", name=op.f("pk_campaign_accounts")),
    )
    op.create_table(
        "campaign_preparation_jobs",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("completed", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_campaign_preparation_jobs_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_preparation_jobs_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_preparation_jobs")),
        sa.UniqueConstraint("campaign_id", name=op.f("uq_campaign_preparation_jobs_campaign_id")),
    )
    op.create_table(
        "photo_selection_sessions",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("community_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("content_hint", sa.String(length=500), nullable=True),
        sa.Column("baseline_rank", sa.Integer(), nullable=False),
        sa.Column("proposed_rank", sa.Integer(), nullable=False),
        sa.Column("learned_rank", sa.Integer(), nullable=True),
        sa.Column("chosen_rank", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ranking_model_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_photo_selection_sessions_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
            name=op.f("fk_photo_selection_sessions_community_id_communities"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_photo_selection_sessions_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photo_selection_sessions")),
    )
    op.create_index(
        op.f("ix_photo_selection_sessions_campaign_id"),
        "photo_selection_sessions",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photo_selection_sessions_confirmed_at"),
        "photo_selection_sessions",
        ["confirmed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photo_selection_sessions_submission_id"),
        "photo_selection_sessions",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "photo_selection_candidates",
        sa.Column("selection_session_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_identity", sa.String(length=100), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=True),
        sa.Column("preview_id", sa.Uuid(), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("displayed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("operator_rating", sa.String(length=10), nullable=True),
        sa.CheckConstraint(
            "rank >= 1 AND rank <= 12", name=op.f("ck_photo_selection_candidates_rank_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_photo_selection_candidates_media_asset_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["preview_id"],
            ["photo_preview_cache.id"],
            name=op.f("fk_photo_selection_candidates_preview_id_photo_preview_cache"),
        ),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["community_reference_photos.id"],
            name=op.f("fk_photo_selection_candidates_reference_id_community_reference_photos"),
        ),
        sa.ForeignKeyConstraint(
            ["selection_session_id"],
            ["photo_selection_sessions.id"],
            name=op.f(
                "fk_photo_selection_candidates_selection_session_id_photo_selection_sessions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "selection_session_id", "rank", name=op.f("pk_photo_selection_candidates")
        ),
    )
    op.add_column(
        "accounts", sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("accounts", sa.Column("campaign_send_quota", sa.Integer(), nullable=True))
    op.create_unique_constraint("uq_accounts_vk_user_id", "accounts", ["vk_user_id"])
    op.add_column(
        "campaigns",
        sa.Column("photo_review_mode", sa.String(length=24), server_default="AUTO", nullable=False),
    )
    op.add_column(
        "campaigns",
        sa.Column(
            "preparation_state", sa.String(length=24), server_default="legacy", nullable=False
        ),
    )
    op.add_column(
        "submissions",
        sa.Column(
            "ranking_model_version",
            sa.String(length=100),
            server_default="deterministic-v1",
            nullable=False,
        ),
    )
    op.add_column(
        "submissions",
        sa.Column(
            "photo_attention",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("submissions", "photo_source")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "photo_attention")
    op.drop_column("submissions", "ranking_model_version")
    op.drop_column("campaigns", "preparation_state")
    op.drop_column("campaigns", "photo_review_mode")
    op.drop_constraint("uq_accounts_vk_user_id", "accounts", type_="unique")
    op.drop_column("accounts", "campaign_send_quota")
    op.drop_column("accounts", "last_validated_at")
    op.drop_table("photo_selection_candidates")
    op.drop_index(
        op.f("ix_photo_selection_sessions_submission_id"), table_name="photo_selection_sessions"
    )
    op.drop_index(
        op.f("ix_photo_selection_sessions_confirmed_at"), table_name="photo_selection_sessions"
    )
    op.drop_index(
        op.f("ix_photo_selection_sessions_campaign_id"), table_name="photo_selection_sessions"
    )
    op.drop_table("photo_selection_sessions")
    op.drop_table("campaign_preparation_jobs")
    op.drop_table("campaign_accounts")
    op.drop_table("photo_ranking_preferences")
    op.drop_table("photo_ranking_models")
    # ### end Alembic commands ###
